# Alembic migration script template
"""initial_migration

Revision ID: 8fd52cbe9319
Revises: 
Create Date: 2025-12-06 19:57:41.373926

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8fd52cbe9319'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('_user_',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=512), nullable=False),
    sa.Column('name', sa.String(length=512), nullable=True),
    sa.Column('password', sa.String(length=512), nullable=False),
    sa.Column('email', sa.String(length=512), nullable=False),
    sa.Column('last_login', sa.Date(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username', 'email', name='_user_username_email_key')
    )
    op.create_index(op.f('ix__user__id'), '_user_', ['id'], unique=False)
    op.create_table('cast',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.Column('nationality', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cast_id'), 'cast', ['id'], unique=False)
    op.create_table('director',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('nationality', sa.String(length=512), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_director_id'), 'director', ['id'], unique=False)
    op.create_table('genre',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=512), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_index(op.f('ix_genre_id'), 'genre', ['id'], unique=False)
    op.create_table('movie',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(length=524), nullable=False),
    sa.Column('launch_date', sa.Date(), nullable=True),
    sa.Column('description', sa.String(length=512), nullable=True),
    sa.Column('nationality', sa.String(length=512), nullable=True),
    sa.Column('poster_path', sa.String(length=512), nullable=True),
    sa.Column('avg_rating', sa.Numeric(precision=3, scale=1), nullable=True),
    sa.Column('count_rating', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_movie_name', 'movie', ['name'])
    
    # Relationship tables (many-to-many)
    op.create_table('director_movie',
    sa.Column('director_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['director_id'], ['director.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('director_id', 'movie_id')
    )
    op.create_table('genre_movie',
    sa.Column('genre_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['genre_id'], ['genre.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('genre_id', 'movie_id')
    )
    op.create_table('movie_cast',
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.Column('cast_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['cast_id'], ['cast.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('movie_id', 'cast_id')
    )
    op.create_table('rating',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('evaluation', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('movie_id', sa.Integer(), nullable=False),
    sa.CheckConstraint('evaluation >= 1 AND evaluation <= 5', name='evaluation_check'),
    sa.ForeignKeyConstraint(['movie_id'], ['movie.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['_user_.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_rating_id'), 'rating', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_rating_id'), table_name='rating')
    op.drop_table('rating')
    op.drop_table('movie_cast')
    op.drop_table('genre_movie')
    op.drop_table('director_movie')
    op.drop_index(op.f('ix_movie_id'), table_name='movie')
    op.drop_table('movie')
    op.drop_index(op.f('ix_genre_id'), table_name='genre')
    op.drop_table('genre')
    op.drop_index(op.f('ix_director_id'), table_name='director')
    op.drop_table('director')
    op.drop_index(op.f('ix_cast_id'), table_name='cast')
    op.drop_table('cast')
    op.drop_index(op.f('ix__user__id'), table_name='_user_')
    op.drop_table('_user_')
    # ### end Alembic commands ###
