FROM docker.io/library/python:3.12-alpine

WORKDIR /app

COPY app .
COPY requirements.txt .

RUN pip install --no-cache-dir -r requirements.txt

CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "5000"]