build:
  stage: build
  parallel:
    matrix:
      - IMAGE_NAME: api
        CONTEXT_PATH: ./src/api
      - IMAGE_NAME: web
        CONTEXT_PATH: ./src/web
  before_script:
    - echo "$CI_REGISTRY_PASSWORD" | docker login -u "$CI_REGISTRY_USER" --password-stdin "$CI_REGISTRY"
  script:
    - echo "Building image - $IMAGE_NAME"
    - docker build -t $CI_REGISTRY_IMAGE/${IMAGE_NAME}:latest ${CONTEXT_PATH}
    - echo "Pushing image - $IMAGE_NAME"
    - docker push $CI_REGISTRY_IMAGE/${IMAGE_NAME}:latest
    - echo "Saving artifact for image - $IMAGE_NAME"
    - docker save -o ${IMAGE_NAME}-image.tar $CI_REGISTRY_IMAGE/${IMAGE_NAME}:latest
    - echo "Removing local image - $IMAGE_NAME to free space"
    - docker rmi $CI_REGISTRY_IMAGE/${IMAGE_NAME}:latest
  artifacts:
    paths:
      - "*-image.tar"
    expire_in: 1 week
  tags:
    - shell